ekf_filter_node:
  frequency: 30.0
  sensor_timeout: 0.1
  two_d_mode: true
  publish_tf: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /rtabmap/odom
  imu0: /compass/data
  imu0_config: [false, false, false,  
                false, false, false,  
                true, true, true,     
                false, false, false,  
                false, false, false]  

  laser0: /distance_scan
  laser0_config: [true, true, false,  
                  false, false, false,  
                  false, false, false]  

  process_noise_covariance: [0.05, 0,    0,    0,    0,    0,  
                             0,    0.05, 0,    0,    0,    0,  
                             0,    0,    0.01, 0,    0,    0,  
                             0,    0,    0,    0.01, 0,    0,  
                             0,    0,    0,    0,    0.01, 0,  
                             0,    0,    0,    0,    0,    0.01]
